language: node_js
node_js:
  - "node"
sudo: false
cache:
  yarn: true
  directories:
  - node_modules # NPM packages
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn run lint
  - yarn test
branches:
  only:
    - master
